# .goreleaser.yml
project_name: autoscan

# Build
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    main: ./cmd/{{ .ProjectName }}
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "main.Version=v{{ .Version }}"
      - -X "main.GitCommit={{ .ShortCommit }}"
      - -X "main.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm64

# MacOS Universal Binaries
universal_binaries:
  - replace: true

# Archive
archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: "binary"

# Checksum
checksum:
  name_template: "checksums.txt"
  algorithm: sha512

# Changelog
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge branch"

# Docker
dockers:
  - image_templates:
      - "jonathanlew1s/autoscan:v{{ .Version }}-amd64"
      - "ghcr.io/jonathanlew1s/autoscan:v{{ .Version }}-amd64"
    dockerfile: ./apps/{{ .ProjectName }}/Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.description=Autoscan for Plex, Emby and Jellyfin with docker mod support"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "jonathanlew1s/autoscan:v{{ .Version }}-arm64"
      - "ghcr.io/jonathanlew1s/autoscan:v{{ .Version }}-arm64"
    dockerfile: ./apps/{{ .ProjectName }}/Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.description=Autoscan for Plex, Emby and Jellyfin with docker mod support"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "jonathanlew1s/autoscan:v{{ .Version }}"
    image_templates:
      - "jonathanlew1s/autoscan:v{{ .Version }}-amd64"
      - "jonathanlew1s/autoscan:v{{ .Version }}-arm64"
  - name_template: "ghcr.io/jonathanlew1s/autoscan:v{{ .Version }}"
    image_templates:
      - "ghcr.io/jonathanlew1s/autoscan:v{{ .Version }}-amd64"
      - "ghcr.io/jonathanlew1s/autoscan:v{{ .Version }}-arm64"
  - name_template: "{{ if not .IsNightly }}jonathanlew1s/autoscan:latest{{ end }}"
    image_templates:
      - "jonathanlew1s/autoscan:v{{ .Version }}-amd64"
      - "jonathanlew1s/autoscan:v{{ .Version }}-arm64"
  - name_template: "{{ if not .IsNightly }}ghcr.io/jonathanlew1s/autoscan:latest{{ end }}"
    image_templates:
      - "ghcr.io/jonathanlew1s/autoscan:v{{ .Version }}-amd64"
      - "ghcr.io/jonathanlew1s/autoscan:v{{ .Version }}-arm64"
